name: Build and Push to ACR
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemocd6nhom8.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t acrdemocd6nhom8.azurecr.io/webapp:v1.0
        docker push acrdemocd6nhom8.azurecr.io/webapp:v1.0